### ISSUE TITLE
Improve the feel of the toy demos

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/godot-steering-toolkit#3]
The demos currently feel slow. Do a quick pass to improve the feel and look of the demos, using simple visuals.

**Comment by NathanLovato** [comment]
@razcore-art for the UI widgets you could make some reusable container or bit of interface that's shared between all demos. Also use sliders for values instead of LineEdit. Or something easier to tweak and control at least.

**Comment by Razoric480** [comment]
This issue will also address replacing the GUI with just using the inspector - export variables on the main Demo node, ensure that the game window stays on top, and keep scene syncing on and it works perfectly without an extraneous GUI that needs to be kept in sync.

Later on, we can consider adding a manner of automatically GUI generator where you feed it data and it automatically binds itself, but for now the inspector should keep things simple.

**Comment by razcore-art** [comment]
We should also make the demos look more like the GDQuest theme/style. The one that we used for the [beginner 2D platformer](https://github.com/GDQuest/godot-beginner-2d-platformer)

**Comment by NathanLovato** [comment]
You should coordinate with @henriiquecampos, I assigned him to the issue of creating the visual style guide: https://github.com/GDQuest/website/issues/157

**Comment by NathanLovato** [comment]
The gdquest theme repository currently has a theme that's more for debugging, panels with a flat design and dark background. It's going to look mostly like desktop program interfaces, just so you know.
