### ISSUE TITLE
API reference writing and maintenance

### ISSUE THREAD

**Issue by Razoric480** [GDQuest/godot-steering-toolkit#8]
This issue focuses on the need to have a way to create documentation for API, class-sets and other code-centric assets.

Ideally we could come up with something that works as nice as Godot's references, or Stripes' (probably Godot's since GDQuest's docs system works on the same one Godot uses.)

GDScript currently lacks a way to extract docstrings to create a documentation easily, unlike a tool like JavaDoc, doxygen, or Sphinx. So we would either need to either create a tool, tie into another, or extract the code into a JSON dump for documentation.

Nathan's comments on the matter, just to get the conversation resumed:  
> Thanks! I wish GDScript had something like Python, where we can extract docstrings.
> 
> When it comes to writing the API, I'd follow the guidelines from another project or company that has great API ref. We can follow the ones from Godot.
> 
> Also, I'd write a tool to make it easier to document our APIs, but that may require us to have a programming guideline to differentiate private and virtual functions. So, we'd probably need to use two leading underscores for private stuff, as in Python.
> 
> How about the place to write the reference? I'd like to have the equivalent of Python's docstrings in the source code. That way, any dev or user contributing a change will know where to update the function description. A script could then extract these docstrings. There's a problem with that though, it makes the code full of comments and a bit cumbersome to update:
```ruby
# Caps the agent's movement speed.
var speed_max := 0.0
# Controls the inertia of the agent.
var drag := 1.0
```
> Thinking about it though, creating a tool should mean that for compatibility, the API shouldn't change that much once we release the first version. Closed to modification, opened to extension, right.
> 
> It's just a pity that, unlike in Python, we don't have a built-in mechanism in GDScript to document the code.
> 
> The other efficient option is to have a tool like in the Godot repository, that collects all the functions and dumps them to a JSON file, in which we then write the docs. I could use https://github.com/Scony/godot-gdscript-toolkit to make that quickly, it features a GDScript parser.
> 
> In either case, we can have an extensible JSON file to generate the docs from, with fields like:
> 
> - description, possibly the docstring extracted from the source code
> - example, a code example in gdscript
> - tags, possibly extracted from the source code
>
> What do you think?

Worth pointing out that whatever we go with is likely to be carried over into other projects. The toolkit just happens to be the first main API we've got going.

**Comment by NathanLovato** [comment]
Do you mind having comments in the source code? It's something we can safely try and change later:

1. Whether we extract the reference from inline comments or write it directly in a JSON or csv file, we'll need that intermediate JSON or csv to generate the final content.
2. The program that extracts the docstrings from the could would find all the relevant comments, so it's easy to then remove them.

**Comment by Razoric480** [comment]
I think having comments in the code would be part and parcel with a lot of writing projects. The vast majority of systems will have the comments alongside the code and the documentation generated from that.

The downsides is that it will make classes a little more dense and long because of comments, but while making changes to the code structure will mean also writing changes to comments, it's not that bad a price to pay for the flexibility of just running a .GD file into a parser.

Having a separate JSON or CSV file would let our classes be cleaner, but would mean that we now have to synchronize code to data dump, data dump to already-commented data. So anything we use would need to be able to merge correctly with minimal pain.

**Comment by NathanLovato** [comment]
> Having a separate JSON or CSV file would let our classes be cleaner, but would mean that we now have to synchronize code to data dump, data dump to already-commented data. So anything we use would need to be able to merge correctly with minimal pain.

The reason we need to dump that data is that converting straight from the source code becomes tricky when you want examples, markup, etc. I'm thinking about code examples in particular, that may add too many comments to some source files. Comments that we cannot fold. Imagine we also someday make a plugin and want to provide built-in reference in Godot, we'd have the data ready. 

It's easy to sync data with Python, you only need some manual input when renaming parts of the API - which ideally we shouldn't have to do.

Syncing is about as simple as:

```py
old_data = json.load(...)
new_dict = {key: old_data(key) for key in get_all_symbols()}
json.dump(new_dict, ...)
```

With maybe some extra validation

**Comment by Razoric480** [comment]
Good to know, and informative!

I'll rightly admit that I've not poked at documenting a code base very seriously outside of faffing around with doxygen a couple of times, and seeing how codebases are documented in-code (as in JavaDoc.) So this will be a learning experience.

**Comment by Razoric480** [comment]
[NaturalDocs](https://www.naturaldocs.org/) seems a very easy implementation that can work with any language at a basic level just by editing a couple config files - certainly was easy to make work with GDScript with simple commenting tags like "Class: Name" and "Function:", "Parameters:", etc.

But I'm not a fan of its export format and it doesn't have a way to override it easily without rebuilding the C# project with new code. It uses Mono on Linux and Mac, which may also not be ideal.

**Comment by NathanLovato** [comment]
I think a custom solution will do the job. In Godot, you'll already get completion for the function names and variable types.
