### ISSUE TITLE
AvoidCollisionsDemo - posmodv is a nonexistent function

### ISSUE THREAD

**Issue by Kramchay-Dig** [GDQuest/godot-steering-toolkit#9]
**I'm submitting a...**

- [ ] Bug report.

## Bug report ##

![Godot_Issue_0_0](https://user-images.githubusercontent.com/27763628/72958146-34bda080-3de1-11ea-937b-e6f20f2cf554.png)

I went and open the AvoidCollisionsDemo but I ran into a problem in Line 39 that posmodv is a nonexistent function. Any way to fix the bug?

**Comment by johnnygossdev** [comment]
This function was added recently to the engine (in the last 6 months) so may not be in the version of Godot you are using.

https://github.com/godotengine/godot/commit/092346d82b9e3a7e3f957e7d239db09fc4b4a0c4

You can download the 3.2 release candidate from the website which includes this function.

**Comment by Kramchay-Dig** [comment]
> This function was added recently to the engine (in the last 6 months) so may not be in the version of Godot you are using.
> 
> [godotengine/godot@092346d](https://github.com/godotengine/godot/commit/092346d82b9e3a7e3f957e7d239db09fc4b4a0c4)
> 
> You can download the 3.2 release candidate from the website which includes this function.

Ah I see, I'm using Godot 3.1 thank you for the reply.

**Comment by johnnygossdev** [comment]
No problem!
